# Run on all networks, still apply settings to defined networks

[conf]
network_filter="off"

[networks.home]
router_ssid="HomeNet"
ssl=false
login_enforced=false
listen_ip="auto"
listen_port=80

[networks.work]
router_ssid="WorkNet"
ssl=true
login_enforced=true
listen_ip="10.68.100.94"
listen_port=443
http_redirect_port=80

[undefined_networks]
ssl=true
login_enforced=true
listen_ip="auto"
listen_port=4433
